name: scheduled-build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

permissions:
  contents: read

concurrency:
  group: scheduled-build-master
  cancel-in-progress: true

jobs:
  build-android-debug:
    runs-on: ubuntu-22.04
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.x"
          cache: true

      - name: Restore packages
        working-directory: simple_live_app
        run: flutter pub get

      - name: Build APK (debug)
        working-directory: simple_live_app
        run: flutter build apk --debug --split-per-abi

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk-${{ github.run_number }}
          path: simple_live_app/build/app/outputs/flutter-apk/*-debug.apk
